name: asd2
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  camera_camera: ^1.0.34+1
  path_provider: ^1.6.14
  camera: ^0.5.8+5
  tflite: ^1.0.5
  percent_indicator: ^2.1.7+4
  tflite_flutter_helper: ^0.1.2
  tflite_flutter: ^0.5.0
  image: ^2.1.19


dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets: 
    - assets/emotion_model22.tflite
    - assets/model1.tflite
    - assets/model.tflite
    - assets/classifier.tflite
    - assets/labels.txt
